[project]
name = "ruokalista"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "datetime>=6.0",
    "discord>=2.3.2",
    "discord-py>=2.7.1",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
ruokalista = "ruokalista:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
